In [1]:
# ============================================================================
#  CONFIGURATION — les deux blocs à adapter
# ============================================================================
PROJET = r"C:\Users\semy4\OneDrive\Bureau\Fintech_project"

import os, warnings
import numpy as np
import pandas as pd

DATA = os.path.join(PROJET, "data", "processed")
DOCS = os.path.join(PROJET, "docs")
os.makedirs(DOCS, exist_ok=True)
pd.set_option("display.width", 170); pd.set_option("display.max_columns", 80)

# --- Bloc 1 : où sont les fichiers ------------------------------------------
MESSAGES   = os.path.join(DATA, "02_StockTwits_SCORED_2020_2022.csv")  
FINANCE    = os.path.join(DATA, "finance_2020_2022_5T.csv")
SORTIE     = os.path.join(DATA, "PANEL_SENTIMENT_WINDOWS_2020_2022_v2.csv")

# --- Bloc 2 : le fuseau des horodatages SOURCE ------------------------------
# StockTwits renvoie de l'UTC. Si tes horodatages sont déjà en heure de New York,
# mets "America/New_York". Si tu n'es pas sûr, le §2 contient un test de diagnostic.
TZ_SOURCE = "UTC"
TZ_MARCHE = "America/New_York"

TICKERS = ["AAPL", "AMZN", "META", "NVDA", "TSLA"]
DEBUT, FIN = "2020-01-02", "2022-03-04"


def charger(chemin):
    ext = os.path.splitext(chemin)[1].lower()
    if ext == ".pkl":     return pd.read_pickle(chemin)
    if ext == ".parquet": return pd.read_parquet(chemin)
    return pd.read_csv(chemin)


msg = charger(MESSAGES)
print(f"{len(msg):,} messages chargés")
print(f"Colonnes disponibles :\n  {list(msg.columns)}")
print(f"\nAperçu :")
print(msg.head(3).to_string())

3,711,333 messages chargés
Colonnes disponibles :
  ['Tweet', 'Ticker', 'Jour', 'Heure_decimale', 'Texte_Nettoye', 'FinBERT_Positive', 'FinBERT_Negative', 'FinBERT_Neutral']

Aperçu :
                                                                                                            Tweet Ticker        Jour  Heure_decimale                                                                                                   Texte_Nettoye  FinBERT_Positive  FinBERT_Negative  FinBERT_Neutral
0  $AAPL good things happening 2020 run trump and everything’s gonna run up get it while you can follow the trend   AAPL  2020-01-01        0.100000  $AAPL good things happening 2020 run trump and everything’s gonna run up get it while you can follow the trend          0.200863      2.107586e-03         0.797029
1                           $AAPL Happy New Year amazing winning AAPL Bulls! You’re making life fun and exciting!   AAPL  2020-01-01        0.133333                           $AAPL Happy New Year amazing winning AAPL Bulls! You’re making life fun and exciting!          0.999996      4.646351e-07         0.000004
2                                                              Happy New Year  :)\n$AAPL $TSLA $AMZN  $SPY $BTC.X   AAPL  2020-01-01        0.233333                                                                 Happy New Year :) $AAPL $TSLA $AMZN $SPY $BTC.X          0.000071      1.083000e-05         0.999918

In [4]:
df_finance=pd.read_csv(FINANCE)

In [5]:
df_finance.head()

         Date       Open       High        Low      Close     Volume Ticker  prev_close       gap    ret_oc    ret_cc
0  2019-11-01  62.384998  63.982498  62.290001  63.955002  151125200   AAPL         NaN       NaN  0.025166       NaN
1  2019-11-04  64.332497  64.462502  63.845001  64.375000  103272000   AAPL   63.955002  0.005903  0.000661  0.006567
2  2019-11-05  64.262497  64.547501  64.080002  64.282501   79897600   AAPL   64.375000 -0.001748  0.000311 -0.001437
3  2019-11-06  64.192497  64.372498  63.842499  64.309998   75864400   AAPL   64.282501 -0.001400  0.001830  0.000428
4  2019-11-07  64.684998  65.087502  64.527496  64.857498   94940400   AAPL   64.309998  0.005831  0.002667  0.008513

In [ ]:
df_finance.isnull().sum()

Date          0
Open          0
High          0
Low           0
Close         0
Volume        0
Ticker        0
prev_close    5
gap           5
ret_oc        0
ret_cc        5
dtype: int64

In [7]:
df_finance.dropna(inplace=True)

In [8]:
df_finance.isnull().sum()

Date          0
Open          0
High          0
Low           0
Close         0
Volume        0
Ticker        0
prev_close    0
gap           0
ret_oc        0
ret_cc        0
dtype: int64

In [9]:
df_finance.head()

         Date       Open       High        Low      Close     Volume Ticker  prev_close       gap    ret_oc    ret_cc
1  2019-11-04  64.332497  64.462502  63.845001  64.375000  103272000   AAPL   63.955002  0.005903  0.000661  0.006567
2  2019-11-05  64.262497  64.547501  64.080002  64.282501   79897600   AAPL   64.375000 -0.001748  0.000311 -0.001437
3  2019-11-06  64.192497  64.372498  63.842499  64.309998   75864400   AAPL   64.282501 -0.001400  0.001830  0.000428
4  2019-11-07  64.684998  65.087502  64.527496  64.857498   94940400   AAPL   64.309998  0.005831  0.002667  0.008513
5  2019-11-08  64.672501  65.110001  64.212502  65.035004   69986400   AAPL   64.857498 -0.002852  0.005605  0.002737

In [10]:
FINANCE_clean    = os.path.join(DATA, "finance_2020_2022_5T_clean.csv")

In [11]:
df_finance.to_csv(FINANCE_clean, index=False)